# -*- coding: utf-8 -*-
"""
本次新增的装备技能注册表（2026-08-25，依据 Excel 装备表“套装/装备技能”列批量写入）。
已存在的装备技能（风暴降临、神风烈火、混沌初开、光暗侵蚀、悲恸光环、黄昏时刻、
黄昏时刻·永恒、噬浪突袭、冥域、赐剑长驱、暗影狂袭、破穿棘刺、遮天蔽日、轻盈之语、
地脉冲爆、绝对防御、天命所归、长明无忧、幽幕暴动）不在此表中，也不做更改。

说明：
- 套装技能按“拥有套装中任意一件装备即解锁”的简化方式处理，方便使用。
- “攻守兼备”（永恒枪盾）因该装备已有技能“黄昏时刻·永恒”，按“已有技能不更改”原则不重复写入。
"""

# 技能ID从 -100 开始分配（已有装备技能占 -1 ~ -19）
NEW_EQUIPMENT_SKILLS = {
    '亘古庇佑': dict(id=-100, type='active', energy_cost=20, cooldown=20, duration=2, target='self',
                     desc='耗能20，CD20：最终受伤减免100%，持续2回合'),
    '亚龙威仪': dict(id=-101, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：第1回合攻击力提升50%'),
    '亡者均衡': dict(id=-102, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：敌方生命≥50%时最终受伤-(3+能量*0.01)%；<50%时最终伤害+(3+能量*0.01)%'),
    '仲裁': dict(id=-103, type='passive', energy_cost=0, cooldown=0, duration=-1, target='enemy',
                 desc='被动：第3回合开始，敌方防御-15%'),
    '低语回响': dict(id=-104, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：普攻附带(能量*0.02+护甲强化等级+饰品强化等级)真实伤害'),
    '光阴之力': dict(id=-105, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：攻击+15，破甲+15，敏捷+15'),
    '光阴疾斩': dict(id=-106, type='active', energy_cost=28, cooldown=12, duration=1, target='enemy',
                     desc='耗能28，CD12：造成攻击*1.3+敏捷*0.65+最大能量*0.5伤害，并必中1回合'),
    '吞噬': dict(id=-107, type='active', energy_cost=45, cooldown=30, duration=2, target='enemy',
                 desc='耗能45，CD30：造成(最大能量+最大生命)*0.1真实伤害（不暴击），并眩晕2回合'),
    '哀霜咏叹': dict(id=-108, type='active', energy_cost=28, cooldown=12, duration=5, target='enemy',
                     desc='耗能28，CD12：造成攻击+最大能量*0.8伤害，敌方防御/敏捷各-(15+能量*0.01)%，持续5回合'),
    '回溯织线': dict(id=-109, type='active', energy_cost=35, cooldown=18, duration=3, target='self',
                     desc='耗能35，CD18：恢复最大生命*0.2+最大能量*0.1，最终受伤-(20+能量*0.01)%，持续3回合'),
    '守护': dict(id=-110, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                 desc='被动：最终受伤-5%'),
    '封灵暗幕': dict(id=-111, type='active', energy_cost=20, cooldown=12, duration=5, target='enemy',
                     desc='耗能20，CD12：敌方攻击-(15+能量*0.02)%、治疗-40%，持续5回合'),
    '封灵诀': dict(id=-112, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                   desc='被动：能量上限-10%，获得等量敏捷提升（敏捷+最大能量*0.1）'),
    '山崩地裂': dict(id=-113, type='active', energy_cost=50, cooldown=35, duration=10, target='enemy',
                     desc='耗能50，CD35：敌方敏捷-50%，持续10回合，并造成最大生命*0.8伤害'),
    '岩核蓄热': dict(id=-114, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：攻击+能量*0.03，穿透+(4+能量*0.005)'),
    '岩火守望': dict(id=-115, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：战斗开始格挡+(头盔强化等级+能量*0.04)持续5回合，第6回合暴击+5%'),
    '无量通行': dict(id=-117, type='active', energy_cost=10, cooldown=20, duration=3, target='self',
                     desc='耗能10，CD20：敏捷+(10+饰品强化等级)%，并必中，持续3回合'),
    '日耀审判': dict(id=-118, type='active', energy_cost=50, cooldown=20, duration=2, target='enemy',
                     desc='耗能50，CD20：造成攻击*1.3+暴击*1.2+破甲+最大能量*0.5伤害，自身最终伤害+(5+能量*0.01)%，持续2回合'),
    '日耀裁决': dict(id=-119, type='active', energy_cost=45, cooldown=18, duration=2, target='enemy',
                     desc='耗能45，CD18：造成攻击*1.35+破甲+最大能量*0.5+回合数*4真实伤害，自身最终伤害+(5+能量*0.01)%，持续2回合'),
    '暴风扰动': dict(id=-120, type='passive', energy_cost=0, cooldown=0, duration=-1, target='enemy',
                     desc='被动：每回合使敌方最终伤害-(5+能量*0.01)%'),
    '暴食': dict(id=-121, type='active', energy_cost=50, cooldown=30, duration=10, target='self',
                 desc='耗能50，CD30：降低自身10%当前生命，获得能量*0.03%攻击和暴击加成，每回合恢复能量*0.02生命，持续10回合'),
    '月华守衡': dict(id=-122, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：每回合按敌方血量切换：≥50%时最终受伤-(5+能量*0.01)%；<50%时敏捷+(5+能量*0.01)%'),
    '月华秘钥': dict(id=-123, type='active', energy_cost=20, cooldown=18, duration=5, target='self',
                     desc='耗能20，CD18：恢复最大生命*0.1+最大能量*0.25，最终受伤-(15+能量*0.015)%，持续5回合'),
    '沸血之毒': dict(id=-124, type='active', energy_cost=100, cooldown=100, duration=100, target='enemy',
                     desc='耗能100，CD100：获得攻击*0.03真实伤害附伤（持续整场），造成最大能量*0.1伤害，敌方最终伤害降低最大能量*0.01%，持续100回合'),
    '深渊暴动': dict(id=-125, type='active', energy_cost=30, cooldown=50, duration=6, target='self',
                     desc='耗能30，CD50：暴走6回合：最终伤害+30%、敏捷+50%，每次攻击附带敏捷*0.1真实伤害'),
    '渴血追袭': dict(id=-126, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：每回合恢复0.02*(攻击+敏捷-防御)生命，攻击+能量*0.05'),
    '灵风': dict(id=-127, type='active', energy_cost=1, cooldown=10, duration=2, target='enemy',
                 desc='耗能1，CD10：眩晕敌方2回合'),
    '灼炎领域': dict(id=-128, type='active', energy_cost=30, cooldown=15, duration=8, target='enemy',
                     desc='耗能30，CD15：普攻附加攻击*0.5伤害与最大能量*0.1真实伤害，敌方重伤（治疗-50%），持续8回合'),
    '燃魂之血': dict(id=-129, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：降低最大能量*0.02%最大生命，获得攻击/暴击+最大生命*最大能量*0.00014'),
    '爆裂': dict(id=-130, type='active', energy_cost=10, cooldown=10, duration=0, target='enemy',
                 desc='耗能10，CD10：造成攻击+暴击*0.1+破甲*0.1+防御*0.3伤害'),
    '狩猎形态': dict(id=-131, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：第1回合敏捷+(6+能量*0.01)%，并必中1回合'),
    '王风号令': dict(id=-132, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：敏捷永久+最大能量*0.012%，第1回合必中1回合'),
    '生死均势': dict(id=-133, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：敌方生命≥50%时最终受伤-10%；<50%时最终伤害+10%；攻击/防御各+能量*0.01'),
    '疾焰突袭': dict(id=-134, type='active', energy_cost=10, cooldown=12, duration=2, target='enemy',
                     desc='耗能10，CD12：造成攻击*1.1+敏捷*0.8+最大能量*0.2伤害，敏捷+15%，持续2回合'),
    '瘟骨压迫': dict(id=-135, type='active', energy_cost=18, cooldown=12, duration=6, target='enemy',
                     desc='耗能18，CD12：造成攻击*2+最大生命*0.08伤害，敌方治疗-50%，持续6回合'),
    '瘟骨裂击': dict(id=-136, type='active', energy_cost=20, cooldown=15, duration=5, target='enemy',
                     desc='耗能20，CD15：造成攻击*1.5+最大生命*0.05+最大能量*0.4伤害，敌方治疗-(35+能量*0.02)%，持续5回合'),
    '盛怒绽放': dict(id=-137, type='active', energy_cost=0, cooldown=40, duration=10, target='enemy',
                     desc='耗能25%最大能量，CD40：造成攻击*1.25+当前能量*3伤害，恢复25%已损生命，防御+最大能量*0.01%，持续10回合'),
    '看破': dict(id=-138, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                 desc='被动：暴击+5%，穿透+5%'),
    '瞬时偏移': dict(id=-139, type='active', energy_cost=18, cooldown=10, duration=3, target='self',
                     desc='耗能18，CD10：必闪1回合，敏捷+20%，持续3回合'),
    '破碎碾压': dict(id=-140, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：第5回合开始，穿透+(武器强化+护甲强化)%、最终伤害+能量*0.02%，持续3回合'),
    '磐石': dict(id=-141, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                 desc='被动：格挡+20（最终受伤-20）'),
    '神风': dict(id=-142, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                 desc='被动：敏捷+10%'),
    '祥云消难': dict(id=-143, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：入场最终受伤-(最大能量*0.03)%持续3回合，第1回合恢复10%已损生命'),
    '秘钥开环': dict(id=-144, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：第5回合最终伤害+20%持续2回合，并造成最大能量*2.5伤害'),
    '繁荣不息': dict(id=-145, type='active', energy_cost=0, cooldown=30, duration=30, target='self',
                     desc='耗能护甲强化等级，CD30：每回合恢复(0.1*护甲强化等级)%最大生命，持续30回合，并立刻恢复3%最大生命'),
    '统御者': dict(id=-146, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                   desc='被动：最终伤害+10%'),
    '自然之力': dict(id=-147, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：最大生命+5%，最大能量+5%'),
    '蓄势': dict(id=-148, type='active', energy_cost=60, cooldown=10, duration=1, target='self',
                 desc='耗能60，CD10：最终伤害+(100+能量*0.01)%，最终受伤-(能量*0.05)%，持续1回合'),
    '虚化': dict(id=-149, type='active', energy_cost=10, cooldown=8, duration=5, target='self',
                 desc='耗能10，CD8：必闪1回合，敏捷+25%，持续5回合'),
    '裂岩契约': dict(id=-150, type='active', energy_cost=12, cooldown=6, duration=3, target='enemy',
                     desc='耗能12，CD6：造成攻击*1.3+防御*0.6+最大能量*0.2伤害，敌方防御-12%，持续3回合'),
    '裂鳞护体': dict(id=-151, type='active', energy_cost=12, cooldown=12, duration=3, target='self',
                     desc='耗能12，CD12：恢复最大生命*0.08+最大能量*0.2，最终受伤降低，持续3回合'),
    '赤鳞复燃': dict(id=-152, type='active', energy_cost=15, cooldown=10, duration=5, target='self',
                     desc='耗能15，CD10：恢复最大生命*0.08+最大能量*0.1，最终伤害+12%、普攻附加攻击*0.12伤害，持续5回合'),
    '踏罡裁影': dict(id=-153, type='active', energy_cost=20, cooldown=8, duration=2, target='enemy',
                     desc='耗能20，CD8：造成攻击*1.1+敏捷*0.7伤害，并必中2回合'),
    '轮衡步': dict(id=-154, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                   desc='被动：敏捷+最大能量*0.015%，第1回合必中1回合'),
    '追猎': dict(id=-155, type='active', energy_cost=40, cooldown=20, duration=5, target='enemy',
                 desc='耗能40，CD20：获得敏捷*0.2附伤，持续5回合，并造成攻击*0.25+最大能量*0.1的5次连击'),
    '镇压': dict(id=-156, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                 desc='被动：敌方生命<50%时我方伤害+15%；否则自身免伤+15%'),
    '霜之哀伤': dict(id=-157, type='active', energy_cost=10, cooldown=20, duration=10, target='enemy',
                     desc='耗能10，CD20：敌方防御/敏捷-20%，持续10回合，并造成当前能量*0.5伤害'),
    '风暴穿刺': dict(id=-158, type='active', energy_cost=40, cooldown=12, duration=0, target='enemy',
                     desc='耗能40，CD12：造成攻击*1.25+敏捷*0.65+破甲*0.7+最大能量*0.3伤害'),
    '骇光猎印': dict(id=-159, type='passive', energy_cost=0, cooldown=0, duration=-1, target='self',
                     desc='被动：暴击+(3+能量*0.006)%；第3回合最终伤害+(8+能量*0.01)%，持续2回合'),
    '魔王斩': dict(id=-160, type='active', energy_cost=5, cooldown=5, duration=0, target='enemy',
                   desc='耗能5，CD5：造成攻击*1.2+破甲伤害'),
    '黄昏禁锢': dict(id=-161, type='active', energy_cost=20, cooldown=30, duration=3, target='enemy',
                     desc='耗能20，CD30：眩晕目标3回合，期间目标受到伤害+15%'),
}

# 装备名 -> 技能名列表（拥有任意一件即解锁；套装技能采用单件触发简化）
EQUIPMENT_SKILL_MAP = {
    '隐秘-亘古守卫之靴': ['亘古庇佑'],
    '隐秘-亚龙冠冕': ['亚龙威仪'],
    '死灵均衡铠': ['亡者均衡'],
    '界律仲裁之枪': ['仲裁'],
    '界律镇守之冠': ['仲裁'],
    '耳语帷幕斗篷': ['低语回响'],
    '深渊回响之坠': ['低语回响'],
    '一寸朝夕': ['光阴之力'],
    '一寸暮色': ['光阴之力'],
    '光阴巡猎战刃': ['光阴疾斩'],
    '无尽吞噬甲': ['吞噬'],
    '永饥之环': ['吞噬'],
    '哀霜咏叹杖': ['哀霜咏叹'],
    '时光之瞬面罩': ['回溯织线'],
    '永恒编织者甲胄': ['回溯织线'],
    '光阴秘钥': ['回溯织线', '秘钥开环'],
    '隐秘-守护重锤': ['守护'],
    '永夜封灵冠': ['封灵暗幕', '生死均势'],
    '暗影棱镜': ['封灵暗幕'],
    '夜影封灵靴': ['封灵诀'],
    '撼岳战盔': ['山崩地裂', '爆裂'],
    '地裂蛮神铠': ['山崩地裂', '爆裂'],
    '裂地撼山杵': ['山崩地裂', '爆裂'],
    '崩裂行者': ['山崩地裂', '爆裂'],
    '大地之心': ['山崩地裂', '爆裂'],
    '岩核熔迹环': ['岩核蓄热'],
    '岩火守望冠': ['岩火守望'],
    '隐秘-终界谕令残篇': ['无量通行'],
    '日月天衡冠': ['日耀审判', '月华守衡'],
    '日月裁决': ['日耀审判', '踏罡裁影'],
    '日耀之环': ['日耀审判'],
    '日耀裁决刃': ['日耀裁决'],
    '暴风神甲': ['暴风扰动'],
    '饕餮之冠': ['暴食'],
    '日月踏罡靴': ['月华守衡', '踏罡裁影'],
    '月华之环': ['月华守衡'],
    '月华秘镜': ['月华秘钥'],
    '隐秘-蛇皇之怒': ['沸血之毒'],
    '幽幕灵织袍': ['深渊暴动'],
    '暴动魔核': ['深渊暴动'],
    '流渊穿越者': ['深渊暴动'],
    '赤岚追袭铁面': ['渴血追袭'],
    '灵风鬓冠': ['灵风'],
    '灵风法杖': ['灵风'],
    '灼火地煞': ['灼炎领域'],
    '炎阳明珠': ['灼炎领域'],
    '赤沸怒啸战盔': ['燃魂之血'],
    '沸血战铠': ['燃魂之血'],
    '沸血践踏者': ['燃魂之血'],
    '魔武狩猎者之靴': ['狩猎形态'],
    '风怒战环': ['王风号令'],
    '万风王冠': ['王风号令'],
    '亡者均势之铠': ['生死均势', '瘟骨压迫'],
    '蛟瞳炎冠': ['赤鳞复燃', '疾焰突袭'],
    '赤鳞蜕甲': ['赤鳞复燃'],
    '熔迹蛟靴': ['赤鳞复燃', '疾焰突袭'],
    '流瘟裂骨杵': ['瘟骨压迫'],
    '瘟疫魔刃': ['瘟骨裂击'],
    '荆棘花冠': ['盛怒绽放'],
    '绽放之刺': ['盛怒绽放'],
    '泣血花蕊之坠': ['盛怒绽放'],
    '隐秘-明目之冕': ['看破'],
    '流光行者踏靴': ['瞬时偏移', '秘钥开环'],
    '深渊裂骨锤': ['镇压', '破碎碾压'],
    '骸之王座甲': ['破碎碾压'],
    '上古岩铠': ['磐石'],
    '黑曜石盾刃': ['磐石'],
    '黑曜石头盔': ['磐石'],
    '堕风神甲': ['神风'],
    '飓风神石': ['神风'],
    '隐秘-碧玉天青铠': ['祥云消难'],
    '繁荣腐化之心': ['繁荣不息'],
    '繁荣腐化铠甲': ['繁荣不息'],
    '统领者战袍': ['统御者'],
    '统领者战靴': ['统御者'],
    '统帅之盔': ['统御者'],
    '自然之泪': ['自然之力'],
    '怒涛血狱锤斧': ['蓄势'],
    '虚灵幽骸面罩': ['虚化'],
    '魔灵残响步履': ['虚化'],
    '裂岩战斧': ['裂岩契约'],
    '岩核契约之环': ['裂岩契约'],
    '裂岩赤鳞甲': ['裂鳞护体'],
    '咏叹之杖': ['霜之哀伤'],
    '哀霜献祭法袍': ['霜之哀伤'],
    '风暴戟刃': ['风暴穿刺'],
    '恐惧猎杀之弓': ['骇光猎印'],
    '魔王巨刃': ['魔王斩'],
    '亡者战魂': ['魔王斩'],
    '禁界踏破战靴': ['黄昏禁锢'],
    '守界黄昏': ['黄昏禁锢'],
    '蝠啸裂空镰': ['追猎'],
    '夜蝠追猎履': ['追猎'],
    '深渊王冠': ['镇压'],
    '不灭之心': ['镇压'],
}


def get_new_skill_ids():
    return [v['id'] for v in NEW_EQUIPMENT_SKILLS.values()]


def get_skills_by_equipment(eq_names):
    """根据已装备的装备名列表返回其拥有的新技能定义列表（含 name，去重，保持顺序）。"""
    result = []
    seen = set()
    for ename in eq_names:
        for sname in EQUIPMENT_SKILL_MAP.get(ename, []):
            if sname not in seen and sname in NEW_EQUIPMENT_SKILLS:
                seen.add(sname)
                d = dict(NEW_EQUIPMENT_SKILLS[sname])
                d['name'] = sname
                result.append(d)
    return result
